/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca1dsabiketracker;

/**
 *
 * @author michaelflanagan
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private MyQueue reportQueue;
    private int reportCounter;
    private MyPriorityQueue urgentQueue;
    private MyStack actionStack;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        reportQueue = new MyQueue();
        reportCounter = 1;
        urgentQueue = new MyPriorityQueue();
        actionStack = new MyStack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtReportId = new javax.swing.JTextField();
        txtStationName = new javax.swing.JTextField();
        txtIssueType = new javax.swing.JTextField();
        txtDetails = new javax.swing.JTextField();
        txtSeverity = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDisplayAll = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnDequeueUrgent = new javax.swing.JButton();
        btnRecentAction = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Docklands DublinBikes Tracker");

        jLabel2.setText("Report ID ");

        jLabel3.setText("Station Name");

        jLabel4.setText("Issue Type");

        jLabel5.setText("Details");

        jLabel6.setText("Severity");

        txtReportId.addActionListener(this::txtReportIdActionPerformed);

        txtStationName.addActionListener(this::txtStationNameActionPerformed);

        txtIssueType.addActionListener(this::txtIssueTypeActionPerformed);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDisplayAll.setText("Display All");
        btnDisplayAll.addActionListener(this::btnDisplayAllActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnNext.setText("Next");
        btnNext.addActionListener(this::btnNextActionPerformed);

        btnDequeueUrgent.setText("Dequeue Most Urgent");
        btnDequeueUrgent.addActionListener(this::btnDequeueUrgentActionPerformed);

        btnRecentAction.setText("Recent Action");
        btnRecentAction.addActionListener(this::btnRecentActionActionPerformed);

        jLabel7.setText("Output");

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(78, 78, 78))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addGap(59, 59, 59)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(73, 73, 73)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(97, 97, 97)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(90, 90, 90)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSeverity, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(txtDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(txtIssueType)
                                    .addComponent(txtStationName)
                                    .addComponent(txtReportId))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAdd)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnDisplayAll))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnNext)
                                                    .addComponent(btnUpdate))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnDequeueUrgent)
                                                    .addComponent(btnDelete)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(btnRecentAction))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtReportId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAdd)
                                .addComponent(btnDisplayAll)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtStationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnUpdate)
                                    .addComponent(btnDequeueUrgent))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtIssueType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnNext)
                                    .addComponent(btnDelete))))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRecentAction)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReportIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportIdActionPerformed

    private void txtStationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStationNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStationNameActionPerformed

    private void txtIssueTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIssueTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIssueTypeActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        Object nextReport;
        nextReport = reportQueue.dequeue();
        
        if (nextReport == null){
            txtOutput.setText("Queue is empty");
        } else{
            txtOutput.setText("Next report processed: \n" + nextReport.toString());
            actionStack.push("Processed next report");
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String stationName;
        String issueType;
        String details;
        int severity;
        BikeReport newReport;
        
        stationName = txtStationName.getText();
        issueType = txtIssueType.getText();
        details = txtDetails.getText();
        severity = Integer.parseInt(txtSeverity.getText());
        
        if (issueType.equalsIgnoreCase("Empty") || issueType.equalsIgnoreCase("Full")){
            newReport = new AvailabilityReport(reportCounter, stationName, issueType, details, severity);
        } else{
            newReport = new FaultReport(reportCounter, stationName, issueType, details, severity);
        }
        
        txtReportId.setText(String.valueOf(reportCounter));
        reportQueue.enqueue(newReport.toString());
        urgentQueue.enqueue(severity, newReport.toString());
        actionStack.push("Added report " + reportCounter);
        txtOutput.append(newReport.toString() + "\n");
        reportCounter++;
        
        txtStationName.setText("");
        txtIssueType.setText("");
        txtDetails.setText("");
        txtSeverity.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDisplayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayAllActionPerformed
        // TODO add your handling code here:
        txtOutput.setText("");
        
        MyQueue tempQueue;
        tempQueue = new MyQueue();
        
        while (!reportQueue.isEmpty()){
            String oneReport;
            oneReport = (String) reportQueue.dequeue();
            txtOutput.append(oneReport + "\n");
            tempQueue.enqueue(oneReport);
        }
        
        while (!tempQueue.isEmpty()){
            reportQueue.enqueue(tempQueue.dequeue());
        }
    }//GEN-LAST:event_btnDisplayAllActionPerformed

    private void btnDequeueUrgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDequeueUrgentActionPerformed
        // TODO add your handling code here:
        Object urgentReport;
        urgentReport = urgentQueue.dequeue();
        
        if (urgentReport == null){
            txtOutput.setText("No urgent reports");
        } else{
            txtOutput.setText("Most urgent reports");
            actionStack.push("Dequeued most urgent report");
        }
    }//GEN-LAST:event_btnDequeueUrgentActionPerformed

    private void btnRecentActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecentActionActionPerformed
        // TODO add your handling code here:
        Object recentAction;
        recentAction = actionStack.peek();
        
        if (recentAction == null){
            txtOutput.setText("No recent actions");
        } else{
            txtOutput.setText("Recent action: \n" + recentAction.toString());
        }
    }//GEN-LAST:event_btnRecentActionActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String deleteId;
        deleteId = txtReportId.getText();
        
        MyQueue tempQueue;
        tempQueue = new MyQueue();
        
        while (!reportQueue.isEmpty()){
            String oneReport;
            oneReport = (String) reportQueue.dequeue();
            
            if (!oneReport.contains("Report ID: " + deleteId + ",")){
                tempQueue.enqueue(oneReport);
            }
        }
        
        while (!tempQueue.isEmpty()){
            reportQueue.enqueue(tempQueue.dequeue());
        }
        
        txtOutput.setText("Report deleted if ID is found: " + deleteId);
        actionStack.push("Deleted Report " + deleteId);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String updateId;
        String stationName;
        String issueType;
        String details;
        int severity;
        BikeReport updatedReport;
        
        updateId = txtReportId.getText();
        stationName = txtStationName.getText();
        issueType = txtIssueType.getText();
        details = txtDetails.getText();
        severity = Integer.parseInt(txtSeverity.getText());
        
        if (issueType.equalsIgnoreCase("Empty") || issueType.equalsIgnoreCase("Full")){
            updatedReport = new AvailabilityReport(Integer.parseInt(updateId), stationName, issueType, details, severity);
        } else{
            updatedReport = new FaultReport(Integer.parseInt(updateId), stationName, issueType, details, severity);
        }
        
        MyQueue tempQueue;
        tempQueue = new MyQueue();
        
        while (!reportQueue.isEmpty()){
            String oneReport;
            oneReport = (String) reportQueue.dequeue();
            
            if (oneReport.contains("Report ID: " + updateId + ",")){
                tempQueue.enqueue(updatedReport.toString());
            } else{
                tempQueue.enqueue(oneReport);
            }
        }
        
        while (!tempQueue.isEmpty()){
            reportQueue.enqueue(tempQueue.dequeue());
        }
        
        txtOutput.setText("Report updated for ID: " + updateId);
        actionStack.push("Updated Report " + updateId);
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDequeueUrgent;
    private javax.swing.JButton btnDisplayAll;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnRecentAction;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDetails;
    private javax.swing.JTextField txtIssueType;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JTextField txtReportId;
    private javax.swing.JTextField txtSeverity;
    private javax.swing.JTextField txtStationName;
    // End of variables declaration//GEN-END:variables
}
